### ISSUE TITLE
volume issues

### ISSUE THREAD

**Issue by tonyrel** [arma7x/kaimusic#1]
Hi, it seems have a problem in volume, when i set the volume into full the app seems to low volume unlike the built in audio player from kaios.. i think the problem is from the default volume that you have set? i saw some code from java script just like this
 **_const DEFAULT_VOLUME = 0.02;_** i don't know if i'm correct? can you fix some issues?

**Comment by arma7x** [comment]
Yes, it's bug. Remove line https://github.com/arma7x/kaimusic/blob/master/assets/js/app.js#L204 solve the problem

**Comment by arma7x** [comment]
Thanks @tonyrel

**Comment by arma7x** [comment]
https://github.com/arma7x/kaimusic/commit/fa15870ba405a3f929eae194ac16af6063dac64e
