### ISSUE TITLE
Folder playlist displaces all folders recursively

### ISSUE THREAD

**Issue by helotbc** [arma7x/kaimusic#10]
Folder playlist method is great. It is the only way I can play music in playlists. However, all folders are listed recursively. This makes it hard to find the top level "playlist" folder I created when it is listed among artist and album folders. I recommend that folder view only show the top level folders and allow the user to browse to lower level folders with a Select command. -Brendan

**Comment by arma7x** [comment]
Quite busy to implememt Folder browsing, but this is how FOLDER PLAYLIST sorting works:

FOLDER TREE:
top/artist1/album1/genre1/song1.mp3
top/artist2/album2/genre1/song2.mp3
top/artist2/album2/genre1/favourite/song3.mp3
top/artist2/favourite/song4.mp3

OUTPUT:
top = [song1.mp3, song2.mp3, song3.mp3, song4.mp3]
artist1 = [song1.mp3]
artist2 = [song2.mp3, song3.mp3, song4.mp3]
album1 =[song1.mp3]
album2 = [song2.mp3, song3.mp3]
genre1 = [song1, song2.mp3, song3.mp3]
favourite = [song3.mp3, song4.mp3]

BTW, Folder browsing is a good idea
