### ISSUE TITLE
Fast forwarding doesn't work

### ISSUE THREAD

**Issue by petrkovacs** [arma7x/kaimusic#12]
I am listening to long audio files (almost 2 hours long) and sometimes I need to fast forward the track to a specific position (where I stopped listening last time). I know K-Music remembers the position, but not always. When I try to fast forward the audio track by double pressing right arrow key, I can see the position change and the audio also, but when I release the button the audio track starts to play from the beginning no matter what position I fast forwarded it to. Can you please look at this problem? Thanks a lot.

One more thing about the fast forwarding - I would greatly appreciate some other key to fast forward it more than 10 seconds (which is what double press on right arrow key currently does). Maybe some numeric key could be used (4 to rewind back and 6 to fast forward) to skip 1 minute or maybe more (or better to skip for example 10 % of the duration of the track). What do you think?

**Comment by arma7x** [comment]
File size, duration and MIME  ?

**Comment by petrkovacs** [comment]
The file size is 39 MB, file type is OGG and the track is one hour and 41 minutes long.

**Comment by arma7x** [comment]
Does this bug only occur for file type OGG. If you don't mind, please email to me those file

**Comment by arma7x** [comment]
Rewind/Fast-forward
1 & 4 => 30s
2 & 5 => 60s
3 & 6 => 10%

**Comment by petrkovacs** [comment]
> Rewind/Fast-forward
> 1 & 4 => 30s
> 2 & 5 => 60s
> 3 & 6 => 10%

Great! A little bit better (from the UX perspective) would be 1&3, 4&6, 7&9 because it's horizontal, like the left&right arrows and the progress bar of the audio track. But I will leave it up to you, I will get used to it even vertically :-). Thanks.

**Comment by arma7x** [comment]
> > Rewind/Fast-forward
> > 1 & 4 => 30s
> > 2 & 5 => 60s
> > 3 & 6 => 10%
> 
> Great! A little bit better (from the UX perspective) would be 1&3, 4&6, 7&9 because it's horizontal, like the left&right arrows and the progress bar of the audio track. But I will leave it up to you, I will get used to it even vertically :-). Thanks.

I will change it according to your suggestions

**Comment by arma7x** [comment]
solved https://github.com/arma7x/kaimusic/commit/8cdcc722d7deec819285f95376b59efc8a28cb27
