### ISSUE TITLE
Music in background

### ISSUE THREAD

**Issue by SurferGlobal** [arma7x/kaimusic#14]
When will be there the ability to play music in the background?

**Comment by arma7x** [comment]
K-Music can play the audio in background. Your device ?

**Comment by SurferGlobal** [comment]
Nokia 6300 4G on KaiOS 2.5.4
I’ve tried running it in the background but no luck.

**Comment by arma7x** [comment]
The audio was stopped after you minimize the app Or after you minimize it then open other app ?

**Comment by SurferGlobal** [comment]
After I minimized the app it stops

**Comment by SurferGlobal** [comment]
Here a vid

https://user-images.githubusercontent.com/97216885/150587136-9e0e9257-b748-4472-8746-4f6c27eba7b7.mp4

**Comment by arma7x** [comment]
What happen after you reopen the app ? Does it resume the playback ?

**Comment by arma7x** [comment]
Please follow this to debug:
1) Disable autoplay, Menu > Turn Off Autoplay
2) Play any song then minimize the app(the music should stop playing)
3) Re-open the app. Two possible scenario after this step are:
   a) playback resume(K-Music bug) **OR**
   b) playback does not resume(your device was crashed)

**Comment by arma7x** [comment]
I'm available on Reddit Chat(/u/arma7x) or telegram(t.me/arma7x)

**Comment by SurferGlobal** [comment]
Ok so I disabled auto play, but the music plays in the background. And after I restarted the phone, I turned auto play back on and now it plays in the background when auto play is on or off.

**Comment by arma7x** [comment]
So the problem is solved? right? Maybe a bug and I will investigate this issue 
Consider kill the app if this bug occurs again by clicking **Menu > Kill App**

**Comment by SurferGlobal** [comment]
Yes it’s good now. Thanks
