### ISSUE TITLE
High system resource occupancy rate?

### ISSUE THREAD

**Issue by iamPorter** [arma7x/kaimusic#17]
It seems that when the app opens, the app takes too much system resources, which closes all background apps on KaiOS, including the system homepage. It's rare that a tool app can take up the same resource like a game (e.g.:AirshipCombat3D). Also, when using the app, my device doesn't run it as smoothly as I expected. Is this my problem or there's really something unsatisfying?
Device info: 
Nokia 6300 4G (Qualcomm Snapdragon 210) 
KaiOS 2.5.1
*There are 59 songs detected. All with album cover pictures.

**Comment by arma7x** [comment]
Please disable the equalizer, click Button 0

**Comment by iamPorter** [comment]
OK now I retry, finding that there is nothing to do with equalizer. This time I run the app in background, run"night clock"(Kai store app) and when it's changing songs, it is killed in 4 sec, the same time as reading and showing the detailed information of the song. Happen both when the equalizer is on or off. Please tell me whether it's caused by a song full of basic information, a "high" byte rate(if you think 320kbps is too high for a mp3 file), or a bug.:)-- Sent from Nokia 6300 4Garma7x/kaimusic writes:
Please disable the equalizer

**Comment by arma7x** [comment]
Try reproduce the bug by using built-in audio player and please send the audio to me via ahmadmuhamad101@gmail.com or t.me/arma7x

**Comment by iamPorter** [comment]
OK.
Actually I’ve been using the built-in player in KaiOS all the time, playing all kinds of music (including mp3 and wav)and I have never seen any error from system apps. 
It’s quite wired  that the real time I replied to the issue by email was on June 18 but the time shown here is October 11. During the period I didn’t use the app and now it seems that it works well when dealing with 821 files with equalizer on. Is there any updates during the time?
