### ISSUE TITLE
K-Music skips mp3 files by itself after playing them for 1-2 seconds

### ISSUE THREAD

**Issue by twlswan** [arma7x/kaimusic#18]
title. I downloaded some mp3 files from here https://free-mp3-download.net (eg. this one https://free-mp3-download.net/download.php?id=16921124&q=aGFyZGJvaWxlZA==). They play just fine on my pc. Nonetheless, thanks a lot for your work!

**Comment by arma7x** [comment]
@JakoDel the link expired

**Comment by arma7x** [comment]
This song **Name: Club Dogo - Hardboiled (Sabotatori), Duration: 04:01, BPM: 94, Release date: 2004-01-01**  right ?

I can't reproduce the bug on my Nokia 8110 4G.

**Comment by twlswan** [comment]
> This song **Name: Club Dogo - Hardboiled (Sabotatori), Duration: 04:01, BPM: 94, Release date: 2004-01-01** right ?
> 
> I can't reproduce the bug on my Nokia 8110 4G.

thanks for the reply! Yes that's the one. In the end I found out that the SD was partially corrupted, a quick chkdsk in cmd fixed the problem. The player works flawlessly now :)

**Comment by JakoDel** [comment]
> > This song **Name: Club Dogo - Hardboiled (Sabotatori), Duration: 04:01, BPM: 94, Release date: 2004-01-01** right ?
> > I can't reproduce the bug on my Nokia 8110 4G.
> 
> thanks for the reply! Yes that's the one. In the end I found out that the SD was partially corrupted, a quick chkdsk in cmd fixed the problem. thanks for the player, it works flawlessly
