### ISSUE TITLE
Playback Speed Control

### ISSUE THREAD

**Issue by Eyal-Elbaz** [arma7x/kaimusic#19]
Hello, I wanted to thank you for the perfect app and I wanted to ask if you could add Playback Speed Control to the app.
thanks a-lot!

**Comment by arma7x** [comment]
Goto **Menu** > **Tips & About**, then scroll to **Shorcut Key**
- Button 2 increment by +0.25s
- Button 5 reset to 1x
- Button 8 decrement by -0.25s

**Comment by Eyal-Elbaz** [comment]
thanks!
