### ISSUE TITLE
K-Music does not find any OGG files

### ISSUE THREAD

**Issue by petrkovacs** [arma7x/kaimusic#2]
Hi. I have problem using your K-Music application. My phone can't play MP3 files (Alcatel 3088X, in the manual it says it supports AAC, AAC+, eAAC, AMR, AMR-WB, OGG). So I converted my music collection to OGG format. But K-Music ignores OGG files, it can't find any, even if they are on my SD card.

I tried to put some MP3 files on my SD card and those files I can see in K-Music library. But it won't play them, probably because the phone doesn't support them :-(.

Could you fix the app so it does not ignore the OGG files? Thanks.
Petr

**Comment by petrkovacs** [comment]
I tried to rename OGG file to MP3 and now the K-Music can play this file.

**Comment by arma7x** [comment]
Let me test on my device Nokia 8110 4G

**Comment by arma7x** [comment]
I copy this sample OGG into my phone [https://upload.wikimedia.org/wikipedia/commons/7/79/Example_of_flats_in_music.ogg](https://upload.wikimedia.org/wikipedia/commons/7/79/Example_of_flats_in_music.ogg) but it's not listed in DEFAULT tracklist.

~~Common OGG audio file has MIME `video/ogg`~~, while K-Music only can play audio file with MIME 'audio/*'

**Comment by arma7x** [comment]
Actually KaiOS has bug, its detect OGG MIME as `video/ogg` even if the real MIME is 'audio/ogg'

OGG file for testing [https://upload.wikimedia.org/wikipedia/commons/7/79/Example_of_flats_in_music.ogg](https://upload.wikimedia.org/wikipedia/commons/7/79/Example_of_flats_in_music.ogg)

Test Result:
KaiOS:  **video/ogg**
https://htmlstrip.com/mime-file-type-checker: **audio/ogg**

**Comment by petrkovacs** [comment]
Are you sure about the bug? Because my OGG music files are correctly recognized by the default Music player and are not shown in the default Video player. So I would say those applications handles the MIME type well, otherwise I would see those files in my Video gallery.

**Comment by arma7x** [comment]
Yes, this is the output from my Nokia 8110 4G:

/sdcard1/Music/Example_of_flats_in_music.ogg => video/ogg 
/sdcard1/Music/Jack Stauber - Buttercup.ogg => video/ogg 
/sdcard1/Music/Jack-Stauber-Buttercup-2.ogg => video/ogg

**Comment by arma7x** [comment]
Maybe K-Music should detect 'video/ogg' as audio. I will fix it

**Comment by arma7x** [comment]
K-Music load files from navigator.getDeviceStorage **sdcard** not **music**. I'm prefer using **sdcard** over **music** since it scanning all file formats(include flac & it's playable on real device), but if using **music** it only scanning audio file(include ogg but not flac)

[supported file formats](https://www.reddit.com/r/KaiOS/comments/k3w21l/kaios_phone_can_play_flac_files/gexipdd?utm_source=share&utm_medium=web2x&context=3) 

Solve https://github.com/arma7x/kaimusic/commit/8d352017d380f32bd7c65a6398d26b22d23801af

**Comment by petrkovacs** [comment]
I just found out that you are right about the OGG being recognized as video and not audio. OGG files show correctly in music app and doesn't show in the video gallery, nevertheless when I go to Settings -> Storage -> External -> Media, it counts the space occupied by my OGG music files into the Movies category, which is clearly wrong.
