### ISSUE TITLE
Question: playlist- support

### ISSUE THREAD

**Issue by MitraMai** [arma7x/kaimusic#3]
Hello! Since I don't find anywhere else to ask, I'll ask here:
I don't have an KaiOS- phone yet, but I'm thinking of buying one. But the music app is kind of crucial. And since I have a lot of playlists I want to listen to... So, is it possible to make playlists on the computer, and then transfer them onto the phone/sd-card? Or mount the phone/sd-card on the computer and then make the playlists there? I use linux as my daily OS. 

Regards

MitraMai

**Comment by arma7x** [comment]
You can't create a playlist on computer then transfer it but K-Music support create, update & duplicate playlist
