### ISSUE TITLE
Sort by album and artist

### ISSUE THREAD

**Issue by MitraMai** [arma7x/kaimusic#4]
Hello!
It would be really good if one where able to sort the music by artist and album. Like the player that comes with KaiOS.

**Comment by arma7x** [comment]
I have 250MB of music on my sd card. From your [post](https://www.reddit.com/r/KaiOS/comments/kdis9i/my_thoughts_on_kaios/) on reddit, you have 30GB of music. Does the default music player can detect all music files & sort the music by artist and album ?

I can implement this feature but quite unsure whether KaiOS can handle large music library

**Comment by MitraMai** [comment]
I've at the moment 12 gb on my card, and yes, the default player can sort it by artist, album and songs. There is a short delay while the apps says something in the line of "Scanning for music" but then the music shows up neatly sorted.

**Comment by arma7x** [comment]
Thanks for feedback

**Comment by arma7x** [comment]
Done, new version is 1.0.3. I will push to KaiStore ASAP
