### ISSUE TITLE
Kaimusic crashes when attempting to create play list

### ISSUE THREAD

**Issue by helotbc** [arma7x/kaimusic#6]
I have an Alcatel Flip 3 running KaiOS 2.5.2. I have installed a micro SD card with ~15GB of .mp3 files. I go to create a play list, create a name, click next then enter a letter to search for music. The app freezes at the first letter and then crashes. Can this be fixed?

Thanks, Brendan

**Comment by arma7x** [comment]
You can play DEFAULT playlist ? total files on micro SD card ?

**Comment by helotbc** [comment]
The default play list starts playing and then the app crashes.
On Mon, 2021-01-11 at 08:58 -0800, Ahmad Malik wrote:
> You can play DEFAULT playlist ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 

Thanks,

Brendan Carroll
617.794.8801

**Comment by arma7x** [comment]
1) What is total files on your micro SD card ? 
2) Does 'Submit Report to KaiOS' screen show up after the app crashed ?

**Comment by helotbc** [comment]
I have ~15GB of .mp3 files on the SD card. No, I do not get the "submit
report" window.
On Mon, 2021-01-11 at 12:11 -0800, Ahmad Malik wrote:
> What is total files on your micro SD card ?
> Does 'Submit Report' screen show up after the app crashed ?
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 

Thanks,

Brendan Carroll
617.794.8801

**Comment by arma7x** [comment]
Probably OOM(Out Of Memory) due to large number of files inside micro SD card. 
Does KaiOS default music player can play all the songs ?

**Comment by arma7x** [comment]
I found the bug, will fix it soon

**Comment by helotbc** [comment]
Great! How will I get the update?
-- 

Thanks,

Brendan Carroll
617.794.8801

**Comment by arma7x** [comment]
SOLVE https://www.reddit.com/r/KaiOS/comments/kwhoex/kmusic_drop_support_for_albumsartist_on_v130/

**Comment by helotbc** [comment]
Ahmad, Thanks for your quick turn-around on the fix. When will v 1.3 be
available in the KaiOS store?
On Wed, 2021-01-13 at 07:40 -0800, Ahmad Malik wrote:
> SOLVE 
> https://www.reddit.com/r/KaiOS/comments/kwhoex/kmusic_drop_support_for_albumsartist_on_v130/
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 

Thanks,

Brendan Carroll
617.794.8801
