### ISSUE TITLE
k-music doesn't respond to commands through Blue-Tooth

### ISSUE THREAD

**Issue by helotbc** [arma7x/kaimusic#8]
I have attached my Alcatel Flip 3 to my Honda Accord via Blue Tooth. The player doesn't respond to commands from my car: for example, skip to the next song. -Brendan

**Comment by arma7x** [comment]
K-Music not implement Bluetooth functionality

Edit: bluetooth require **certified** permission. KaiStore reject certified app from 3rd party developer

**Comment by canyouswim** [comment]
are we sure bluetooth requires certified?  the API ref says it's available to both certified as well as privileged apps?

**Comment by arma7x** [comment]
https://developer.kaiostech.com/docs/getting-started/main-concepts/permissions
